'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Automatische My.Settings-Speicherfunktion"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Aimbot() As Boolean
            Get
                Return CType(Me("Aimbot"),Boolean)
            End Get
            Set
                Me("Aimbot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property AimMode() As Integer
            Get
                Return CType(Me("AimMode"),Integer)
            End Get
            Set
                Me("AimMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RangeBased() As Boolean
            Get
                Return CType(Me("RangeBased"),Boolean)
            End Get
            Set
                Me("RangeBased") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property FovRifles() As Integer
            Get
                Return CType(Me("FovRifles"),Integer)
            End Get
            Set
                Me("FovRifles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property SmoothRifles() As Integer
            Get
                Return CType(Me("SmoothRifles"),Integer)
            End Get
            Set
                Me("SmoothRifles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property AimSpotRifles() As Integer
            Get
                Return CType(Me("AimSpotRifles"),Integer)
            End Get
            Set
                Me("AimSpotRifles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property FovPistols() As Integer
            Get
                Return CType(Me("FovPistols"),Integer)
            End Get
            Set
                Me("FovPistols") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property SmoothPistols() As Integer
            Get
                Return CType(Me("SmoothPistols"),Integer)
            End Get
            Set
                Me("SmoothPistols") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property AimSpotPistols() As Integer
            Get
                Return CType(Me("AimSpotPistols"),Integer)
            End Get
            Set
                Me("AimSpotPistols") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property FovSnipers() As Integer
            Get
                Return CType(Me("FovSnipers"),Integer)
            End Get
            Set
                Me("FovSnipers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property AimSpotSnipers() As Integer
            Get
                Return CType(Me("AimSpotSnipers"),Integer)
            End Get
            Set
                Me("AimSpotSnipers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property SleepTime() As Integer
            Get
                Return CType(Me("SleepTime"),Integer)
            End Get
            Set
                Me("SleepTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ESP() As Boolean
            Get
                Return CType(Me("ESP"),Boolean)
            End Get
            Set
                Me("ESP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Toggable() As Boolean
            Get
                Return CType(Me("Toggable"),Boolean)
            End Get
            Set
                Me("Toggable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ESPmode() As Integer
            Get
                Return CType(Me("ESPmode"),Integer)
            End Get
            Set
                Me("ESPmode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Trigger() As Boolean
            Get
                Return CType(Me("Trigger"),Boolean)
            End Get
            Set
                Me("Trigger") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property TriggerMode() As Integer
            Get
                Return CType(Me("TriggerMode"),Integer)
            End Get
            Set
                Me("TriggerMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property RageMode() As Integer
            Get
                Return CType(Me("RageMode"),Integer)
            End Get
            Set
                Me("RageMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DelayTime() As Integer
            Get
                Return CType(Me("DelayTime"),Integer)
            End Get
            Set
                Me("DelayTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DelayAfterShotTime() As Integer
            Get
                Return CType(Me("DelayAfterShotTime"),Integer)
            End Get
            Set
                Me("DelayAfterShotTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Bhop() As Boolean
            Get
                Return CType(Me("Bhop"),Boolean)
            End Get
            Set
                Me("Bhop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Radar() As Boolean
            Get
                Return CType(Me("Radar"),Boolean)
            End Get
            Set
                Me("Radar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Noflash() As Boolean
            Get
                Return CType(Me("Noflash"),Boolean)
            End Get
            Set
                Me("Noflash") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property NoflashMaxAlpha() As Integer
            Get
                Return CType(Me("NoflashMaxAlpha"),Integer)
            End Get
            Set
                Me("NoflashMaxAlpha") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Autopistol() As Boolean
            Get
                Return CType(Me("Autopistol"),Boolean)
            End Get
            Set
                Me("Autopistol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("18")>  _
        Public Property TriggerKey() As Integer
            Get
                Return CType(Me("TriggerKey"),Integer)
            End Get
            Set
                Me("TriggerKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("33")>  _
        Public Property ESPKey() As Integer
            Get
                Return CType(Me("ESPKey"),Integer)
            End Get
            Set
                Me("ESPKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("18")>  _
        Public Property AimKey() As Integer
            Get
                Return CType(Me("AimKey"),Integer)
            End Get
            Set
                Me("AimKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("67")>  _
        Public Property APKey() As Integer
            Get
                Return CType(Me("APKey"),Integer)
            End Get
            Set
                Me("APKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property SmoothSnipers() As Integer
            Get
                Return CType(Me("SmoothSnipers"),Integer)
            End Get
            Set
                Me("SmoothSnipers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255")>  _
        Public Property ESPcolorEnemyVisR() As Integer
            Get
                Return CType(Me("ESPcolorEnemyVisR"),Integer)
            End Get
            Set
                Me("ESPcolorEnemyVisR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255")>  _
        Public Property ESPcolorEnemyVisG() As Integer
            Get
                Return CType(Me("ESPcolorEnemyVisG"),Integer)
            End Get
            Set
                Me("ESPcolorEnemyVisG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ESPcolorEnemyVisB() As Integer
            Get
                Return CType(Me("ESPcolorEnemyVisB"),Integer)
            End Get
            Set
                Me("ESPcolorEnemyVisB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("170")>  _
        Public Property ESPcolorEnemyVisA() As Integer
            Get
                Return CType(Me("ESPcolorEnemyVisA"),Integer)
            End Get
            Set
                Me("ESPcolorEnemyVisA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255")>  _
        Public Property ESPcolorEnemyR() As Integer
            Get
                Return CType(Me("ESPcolorEnemyR"),Integer)
            End Get
            Set
                Me("ESPcolorEnemyR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ESPcolorEnemyG() As Integer
            Get
                Return CType(Me("ESPcolorEnemyG"),Integer)
            End Get
            Set
                Me("ESPcolorEnemyG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ESPcolorEnemyB() As Integer
            Get
                Return CType(Me("ESPcolorEnemyB"),Integer)
            End Get
            Set
                Me("ESPcolorEnemyB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("170")>  _
        Public Property ESPcolorEnemyA() As Integer
            Get
                Return CType(Me("ESPcolorEnemyA"),Integer)
            End Get
            Set
                Me("ESPcolorEnemyA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ESPcolorTeammateR() As Integer
            Get
                Return CType(Me("ESPcolorTeammateR"),Integer)
            End Get
            Set
                Me("ESPcolorTeammateR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255")>  _
        Public Property ESPcolorTeammateG() As Integer
            Get
                Return CType(Me("ESPcolorTeammateG"),Integer)
            End Get
            Set
                Me("ESPcolorTeammateG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ESPcolorTeammateB() As Integer
            Get
                Return CType(Me("ESPcolorTeammateB"),Integer)
            End Get
            Set
                Me("ESPcolorTeammateB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("170")>  _
        Public Property ESPcolorTeammateA() As Integer
            Get
                Return CType(Me("ESPcolorTeammateA"),Integer)
            End Get
            Set
                Me("ESPcolorTeammateA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ESPcolorWeaponsR() As Integer
            Get
                Return CType(Me("ESPcolorWeaponsR"),Integer)
            End Get
            Set
                Me("ESPcolorWeaponsR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ESPcolorWeaponsG() As Integer
            Get
                Return CType(Me("ESPcolorWeaponsG"),Integer)
            End Get
            Set
                Me("ESPcolorWeaponsG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255")>  _
        Public Property ESPcolorWeaponsB() As Integer
            Get
                Return CType(Me("ESPcolorWeaponsB"),Integer)
            End Get
            Set
                Me("ESPcolorWeaponsB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("170")>  _
        Public Property ESPcolorWeaponsA() As Integer
            Get
                Return CType(Me("ESPcolorWeaponsA"),Integer)
            End Get
            Set
                Me("ESPcolorWeaponsA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255")>  _
        Public Property ESPcolorGrenadesR() As Integer
            Get
                Return CType(Me("ESPcolorGrenadesR"),Integer)
            End Get
            Set
                Me("ESPcolorGrenadesR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ESPcolorGrenadesG() As Integer
            Get
                Return CType(Me("ESPcolorGrenadesG"),Integer)
            End Get
            Set
                Me("ESPcolorGrenadesG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255")>  _
        Public Property ESPcolorGrenadesB() As Integer
            Get
                Return CType(Me("ESPcolorGrenadesB"),Integer)
            End Get
            Set
                Me("ESPcolorGrenadesB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("170")>  _
        Public Property ESPcolorGrenadesA() As Integer
            Get
                Return CType(Me("ESPcolorGrenadesA"),Integer)
            End Get
            Set
                Me("ESPcolorGrenadesA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ESPcolorBombR() As Integer
            Get
                Return CType(Me("ESPcolorBombR"),Integer)
            End Get
            Set
                Me("ESPcolorBombR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255")>  _
        Public Property ESPcolorBombG() As Integer
            Get
                Return CType(Me("ESPcolorBombG"),Integer)
            End Get
            Set
                Me("ESPcolorBombG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255")>  _
        Public Property ESPcolorBombB() As Integer
            Get
                Return CType(Me("ESPcolorBombB"),Integer)
            End Get
            Set
                Me("ESPcolorBombB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("170")>  _
        Public Property ESPcolorBombA() As Integer
            Get
                Return CType(Me("ESPcolorBombA"),Integer)
            End Get
            Set
                Me("ESPcolorBombA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property RageAim() As Integer
            Get
                Return CType(Me("RageAim"),Integer)
            End Get
            Set
                Me("RageAim") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Username")>  _
        Public Property UNAME() As String
            Get
                Return CType(Me("UNAME"),String)
            End Get
            Set
                Me("UNAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password")>  _
        Public Property PASSWD() As String
            Get
                Return CType(Me("PASSWD"),String)
            End Get
            Set
                Me("PASSWD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("170")>  _
        Public Property ESPcolorChickenA() As Integer
            Get
                Return CType(Me("ESPcolorChickenA"),Integer)
            End Get
            Set
                Me("ESPcolorChickenA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("200")>  _
        Public Property ESPcolorChickenR() As Integer
            Get
                Return CType(Me("ESPcolorChickenR"),Integer)
            End Get
            Set
                Me("ESPcolorChickenR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ESPcolorChickenG() As String
            Get
                Return CType(Me("ESPcolorChickenG"),String)
            End Get
            Set
                Me("ESPcolorChickenG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property ESPcolorChickenB() As String
            Get
                Return CType(Me("ESPcolorChickenB"),String)
            End Get
            Set
                Me("ESPcolorChickenB") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.quartus.My.MySettings
            Get
                Return Global.quartus.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
